import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import prisma from '../models/prisma';
import { logAudit } from '../utils/audit';

type PDFDoc = InstanceType<typeof PDFDocument>;

export class BoqService {
    async getBoqData(projectId: string) {
        const project = await prisma.project.findUnique({
            where: { id: projectId },
            include: {
                engineer: { select: { name: true } },
                detections: true,
                estimations: { orderBy: { createdAt: 'desc' }, take: 1 },
            },
        });
        if (!project) throw { status: 404, message: 'Project not found' };
        if (project.estimations.length === 0) throw { status: 400, message: 'No estimation found. Run cost calculation first.' };

        const estimation = project.estimations[0];
        const breakdown = (estimation.breakdown as any[]) || [];

        return { project, estimation, breakdown };
    }

    async generatePDF(projectId: string, userId: string): Promise<PDFDoc> {
        const { project, estimation, breakdown } = await this.getBoqData(projectId);

        const doc = new PDFDocument({ margin: 50, size: 'A4' });

        // ─── Header ────────────────────────────────────────────
        doc.fontSize(20).font('Helvetica-Bold').text('Bill of Quantities (BOQ)', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica').fillColor('#666666');
        doc.text(`Project: ${project.name}`, { align: 'left' });
        doc.text(`Location: ${project.location}`);
        doc.text(`Engineer: ${project.engineer.name}`);
        doc.text(`Date: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`);
        doc.text(`Status: ${project.status}`);
        doc.moveDown(1);

        // ─── Summary ───────────────────────────────────────────
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000000').text('Cost Summary');
        doc.moveDown(0.3);
        doc.fontSize(10).font('Helvetica').fillColor('#333333');
        doc.text(`Total Damaged Area: ${estimation.totalArea.toFixed(2)} m²`);
        doc.text(`Material Cost: ₹${estimation.materialCost.toLocaleString('en-IN')}`);
        doc.text(`Labor Cost: ₹${estimation.laborCost.toLocaleString('en-IN')}`);
        doc.text(`Equipment Cost: ₹${estimation.equipmentCost.toLocaleString('en-IN')}`);
        doc.moveDown(0.3);
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#1E3A8A');
        doc.text(`Total Estimated Cost: ₹${estimation.totalCost.toLocaleString('en-IN')}`);
        doc.moveDown(1);

        // ─── Breakdown Table ───────────────────────────────────
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000000').text('Detailed Breakdown');
        doc.moveDown(0.5);

        const tableTop = doc.y;
        const cols = [50, 200, 280, 340, 420, 500];

        // Header row
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#FFFFFF');
        doc.rect(50, tableTop, 500, 20).fill('#1E3A8A');
        doc.fillColor('#FFFFFF');
        doc.text('#', cols[0] + 4, tableTop + 5, { width: 30 });
        doc.text('Item', cols[1] - 44, tableTop + 5, { width: 100 });
        doc.text('Category', cols[2] - 20, tableTop + 5, { width: 60 });
        doc.text('Rate', cols[3] + 5, tableTop + 5, { width: 60 });
        doc.text('Cost', cols[4] + 10, tableTop + 5, { width: 80, align: 'right' });

        let yPos = tableTop + 22;
        doc.font('Helvetica').fontSize(9).fillColor('#333333');

        breakdown.forEach((item: any, i: number) => {
            if (yPos > 750) {
                doc.addPage();
                yPos = 50;
            }
            const bg = i % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
            doc.rect(50, yPos - 2, 500, 18).fill(bg);
            doc.fillColor('#333333');
            doc.text(`${i + 1}`, cols[0] + 4, yPos, { width: 30 });
            doc.text(item.name || '-', cols[1] - 44, yPos, { width: 100 });
            doc.text(item.category || '-', cols[2] - 20, yPos, { width: 60 });
            doc.text(`₹${item.rate?.toLocaleString('en-IN') || 0}`, cols[3] + 5, yPos, { width: 60 });
            doc.text(`₹${item.cost?.toLocaleString('en-IN') || 0}`, cols[4] + 10, yPos, { width: 80, align: 'right' });
            yPos += 18;
        });

        // Footer note
        doc.moveDown(2);
        doc.fontSize(8).fillColor('#92400E');
        doc.text('Note: GST @18% and contractor profit @15% not included. Add as applicable.', 50);

        doc.moveDown(1);
        doc.fontSize(7).fillColor('#94A3B8').text('Generated by Smart Road Estimator v2.1.0', { align: 'center' });

        await logAudit(userId, 'BOQ_EXPORTED_PDF', 'Project', projectId);

        return doc;
    }

    async generateExcel(projectId: string, userId: string): Promise<ExcelJS.Workbook> {
        const { project, estimation, breakdown } = await this.getBoqData(projectId);

        const workbook = new ExcelJS.Workbook();
        workbook.creator = 'Smart Road Estimator';
        workbook.created = new Date();

        const sheet = workbook.addWorksheet('BOQ');

        // ─── Header ────────────────────────────────────────────
        sheet.mergeCells('A1:F1');
        const titleCell = sheet.getCell('A1');
        titleCell.value = 'Bill of Quantities (BOQ)';
        titleCell.font = { size: 16, bold: true, color: { argb: 'FF1E3A8A' } };
        titleCell.alignment = { horizontal: 'center' };

        sheet.getCell('A3').value = 'Project:';
        sheet.getCell('B3').value = project.name;
        sheet.getCell('A4').value = 'Location:';
        sheet.getCell('B4').value = project.location;
        sheet.getCell('A5').value = 'Engineer:';
        sheet.getCell('B5').value = project.engineer.name;
        sheet.getCell('A6').value = 'Date:';
        sheet.getCell('B6').value = new Date().toLocaleDateString('en-IN');
        sheet.getCell('D3').value = 'Total Area:';
        sheet.getCell('E3').value = `${estimation.totalArea.toFixed(2)} m²`;
        sheet.getCell('D4').value = 'Total Cost:';
        sheet.getCell('E4').value = estimation.totalCost;
        sheet.getCell('E4').numFmt = '₹#,##0';

        // ─── Table Headers ─────────────────────────────────────
        const headerRow = sheet.getRow(8);
        headerRow.values = ['#', 'Item', 'Category', 'Unit', 'Rate', 'Cost'];
        headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A8A' } };
        headerRow.alignment = { horizontal: 'center' };

        sheet.columns = [
            { key: 'num', width: 5 },
            { key: 'name', width: 30 },
            { key: 'category', width: 15 },
            { key: 'unit', width: 10 },
            { key: 'rate', width: 15 },
            { key: 'cost', width: 15 },
        ];

        // ─── Data Rows ─────────────────────────────────────────
        breakdown.forEach((item: any, i: number) => {
            const row = sheet.addRow({
                num: i + 1,
                name: item.name,
                category: item.category,
                unit: item.unit || '-',
                rate: item.rate || 0,
                cost: item.cost || 0,
            });
            row.getCell('rate').numFmt = '₹#,##0.00';
            row.getCell('cost').numFmt = '₹#,##0.00';
            if (i % 2 === 1) {
                row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
            }
        });

        // ─── Totals ────────────────────────────────────────────
        const totalRow = sheet.addRow({ num: '', name: 'GRAND TOTAL', category: '', unit: '', rate: '', cost: estimation.totalCost });
        totalRow.font = { bold: true };
        totalRow.getCell('cost').numFmt = '₹#,##0.00';
        totalRow.getCell('cost').font = { bold: true, color: { argb: 'FF1E3A8A' } };

        await logAudit(userId, 'BOQ_EXPORTED_EXCEL', 'Project', projectId);

        return workbook;
    }
}

export const boqService = new BoqService();
